### ISSUE TITLE
We need a robust set of unit tests written.

### ISSUE THREAD

**Issue by MichaelKentBurns** [MichaelKentBurns/BibleModel#4]
I have chose Jest as a unit test framework. 
See https://jestjs.io 
It is a simple npm install for jest.
In that site, choose the Docs section from the title bar. 
It shows how to install and write tests. 
Look for sources that end in .test.js.  For instance one unit test file for Bible.js is Bible.test.js.
You can then run it by simply entering the command 'npm test'.

> 
> michael@Logos BibleModel % **npm test**
> 
> > biblemodel@1.0.0 test
> > jest
> 
>   console.log
>     Bible.js Initializing for the first time
> 
>       at Object.log (Bible.js:29:31)
> ...

**Comment by MichaelKentBurns** [comment]
The first test written is in Bible.test.js and its purpose is to startup the Bible Model and let it get initialized and then make sure that the books array got loaded.  

That simple unit test (and my adhoc testing) show that in my recent refactoring of Bible.js I have somehow broken the state machine.   
There are two ways to run tests to reproduce this:
node Bible.js  >&Notes/runs/Bible.js-2024-11-06.run
and
npm test >&Notes/runs/jest-2024-11-06.run

The normal node execution as well as simply running Bible.js in VS Code show that after all of the "Bible.js Book added:" lines indicating that the books query has been fully processed the StateMachine recognizes that all 66 books are processed, and the list is complete the state machine (records that fact twice) and then just quits.   It also indicates that the next state (4 booksLoaded) is triggered, but the state machine just stops when it should simply proceed to state 4 and others after that.   

But, the jest run gives more information:  
- - - - - - - - 
> console.log
    Bible.js ===================== stateMachine() ending. time= 366.747833

      at log (Bible.js:309:29)


  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "nextTick callback".
- - - - - -  

This confirms that the state machine just stopped (ie returned from Bible.js to the jest test.  However the actual process kept logging (eg. "nextTick callback" and more.   Each occurrence of that contains the very helpful clue: 

-  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Bible.js state is waiting for books to be done loading.".

This is one of the features of JEST and thus its value beyond adhoc testing.  
So, now I need to look at the changes I made recently where I must have dropped a call to wait for the promise.   So, now, I am looking at the recent changes to figure out how I broke it.  

Inspecting my saved runs: specifically TestStatesAndAsych-2024-10-02.run (where it worked properly, and Bible.js.trace.run.2024-11-01.run where it failed.     

Unfortunately I did quite a bit of work between those times, and did not do consistent testing.  

LET THIS BE A LESSON to ME and you, dear reader:   
1) Use your unit testing and save results more often.
2) Do frequent commits when doing extensive work.   I was working on a number of issues, and failed to do smaller commits.   So, I don't know which changes did the breakage. 
3) Run your unit tests BEFORE doing a commit to make sure that commit does not break things.   And only do the commit when the unit tests all pass.   

So, now what I have to do is carefully inspect every change made during that period and see if I can find the problem.   That effort will be recorded in my next comment here.

**Comment by MichaelKentBurns** [comment]
I was able to resolve the main problem and the basic unit test in Bible.test.js now works.   There are still some issues, but the stateMachine does it's job, which at this point is producing and saving the books.json file.

**Comment by MichaelKentBurns** [comment]
After switching the main body of code to ECMA standards (.mjs) I have now figured out the ECMA details for testing, and it's not JEST, but uses the Assert class of v23 and the test files are also now .mjs

I now have both Bible.test.mjs and Book.test.mjs so I can target class specific testing details. 

I can run the tests in the IDE, or in a shell with this:

node --experimental-sqlite --test 
Inside the IDE I have two testing run/debug configurations which can be used to run individual test classes (or debug them): 
    "run Book.test.mjs" 
    "run Bible.test.mjs" - this one throws an error on it's last line (15) due to a bootstrapping issue.   I'll get that fixed soon.   Ignore it for now.

**Comment by MichaelKentBurns** [comment]
As of today I have made some progress on Bible.test.mjs.   There are two tests.
1) Test the single Bible created by initialization and make sure it is correct.
2) Create a second Bible to test if it also gets loaded independent of the first Bible.
Currently the second test fails because I have just started working on supporting more than 1 Bible at a time.   I will add a new issue for the added requirement.   The second test will fail until that is complete.

**Comment by MichaelKentBurns** [comment]
The first test. Book.test.mjs currently has 3 tests.
1) Simply create a book.
2) Check that all attributes are correctly set by the constructor using a canned row.
3) Query that book by its full name, and by an abbreviated name an make sure they are the same.

These tests all pass.

**Comment by MichaelKentBurns** [comment]
A new issue has been created to address test 2 of Bible.test.mjs:
Add support for multiple Bibles to be opened at the same time. #9

**Comment by bahati7** [comment]
I've also tried using Jest but it doesn't work. Have you been able to find another alternative yet?

**Comment by MichaelKentBurns** [comment]
Yes, the replacement for Jest is built into recent versions of Node.

The tests/*.test.mjs files all use these two imports:
import test from 'node:test';
import * as assert from "node:assert";

They are run with these scripts found in the package.json file:

    "testBook": "node --experimental-sqlite tests/Book.test.mjs",
    "testBible": "node --experimental-sqlite tests/Bible.test.mjs",
    "testChapter": "node --experimental-sqlite tests/Chapter.test.mjs",

I've not had much luck with the ability to run a bunch of those in one run.
But, I think that is because of the fact that this project is not only an API that can be used by other packages, but runs as an application itself with this script:
    "main": "node --experimental-sqlite Bible.mjs"

And the fact that it now contains an http server as part of the state machine.   
That is tested with the other two files in the tests directory: testRest.html and testRest.sh.
